services:
  postgres:
    image: postgres:15-alpine
    container_name: notification-postgres
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-notification_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  app:
    build: .
    container_name: notification-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-notification_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TELEGRAM_SLEEP: ${TELEGRAM_SLEEP:-0.2}
      EMAIL_SLEEP: ${EMAIL_SLEEP:-1}
      MAX_RETRIES: ${MAX_RETRIES:-3}
      RETRY_DELAY: ${RETRY_DELAY:-1}
      ERROR_PROBABILITY: ${ERROR_PROBABILITY:-0.1}
      APP_PORT: 8080
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8080


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge # чтобы с хоста был доступ к сети контейнеров